### ISSUE TITLE
Feature: different strategy for "conflict resolution"

### ISSUE THREAD

**Issue by DaEgi01** [algernon-A/ZoningAdjuster#1]
That is an idea that I had for longer but never came around to implement it.
I'd like to see a different strategy for the "conflict resolution" of cells around corners.
It would be nice if we could say that in case of an overlap one road gets priority over the other instead of doing those weird diagonals. It would either be the wider or the more narrow road depending on a hotkey. or a random one in case both have the same width.
![conflict resolution](https://user-images.githubusercontent.com/11689162/107593728-4f430180-6c10-11eb-8972-145782b2d683.png)

**Comment by algernon-A** [comment]
Great minds think alike!  :-)  Currently experimenting with 'oldest road first', but 'widest priority' makes sense (as does hotkey adjustment, of course - if a spare hotkey can be found!)

I've already discovered that it's not as straightfoward as I originally thought (hoped?) it might be, but hopefully I can get there.

**Comment by algernon-A** [comment]
Implemented in 1.0 release via 2827bfd7e7d25d6d40b402254ec5283ee430396b
